version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
    volumes:
      - backend_data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: "http://localhost:8000"
        VITE_BASE: "/"
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  backend_data:
